name: 'Integration Tests'

env:
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
  SEMAPHORE_SKIP_FLAKY_TESTS: 'true'

on:
  push:
  pull_request:

jobs:
  integration-tests:
    name: 'Integration tests'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_APIKEY }}
      
      - name: Classic Protocol Tests
        run: |
          cd test/docker && docker-compose up -d && sleep 30 && cd ../..
          dotnet restore
          cd test/Confluent.Kafka.IntegrationTests && dotnet test -l "console;verbosity=normal" && cd ../..
      
      - name: Consumer Protocol Tests
        run: |
          cd test/docker && docker-compose -f docker-compose-kraft.yaml up -d && cd ../..
          sleep 300
          export TEST_CONSUMER_GROUP_PROTOCOL=consumer
          dotnet restore
          cd test/Confluent.Kafka.IntegrationTests && dotnet test -l "console;verbosity=normal" && cd ../..

  schema-registry-tests:
    name: 'Schema registry and serdes integration tests'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_APIKEY }}
      - name: Run Tests
        run: |
          cd test/docker && docker-compose up -d && cd ../..
          dotnet restore
          cd test/Confluent.SchemaRegistry.Serdes.IntegrationTests && dotnet test -l "console;verbosity=normal" && cd ../..